[tool.poetry]
name = "mysite"
version = "0.1.0"
description = ""
authors = ["robiya07 <obidjonova07@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
